#!/usr/bin/env python3
"""
Interactive wizard that builds the Apollo -> Claude -> Google Sheets -> Gmail
cold-email workflow directly in an n8n instance via its REST API.

Run:
    python scripts/setup_n8n_cold_email.py

Config is read from / saved to scripts/.env (gitignored). Never commit that file.

Notes on Google OAuth2 (Sheets + Gmail):
    n8n's REST API cannot complete an OAuth consent flow on your behalf -
    Google requires an interactive browser redirect. This script creates the
    credential *shells* (client ID/secret) via the API, then prints a link to
    finish "Connect my account" in the n8n editor. Everything else (nodes,
    connections, cron schedule, error handling, activation, test execution)
    is fully automated.
"""
import json
import os
import sys
import time
from pathlib import Path

import requests

SCRIPT_DIR = Path(__file__).resolve().parent
ENV_PATH = SCRIPT_DIR / ".env"

REQUIRED_KEYS = [
    ("N8N_URL", "n8n instance URL (e.g. https://n8n.yourdomain.com)"),
    ("N8N_API_KEY", "n8n API key (n8n UI -> Settings -> API -> Create an API key)"),
    ("CLAUDE_API_KEY", "Claude API key (console.anthropic.com)"),
    ("GOOGLE_OAUTH_CLIENT_ID", "Google OAuth2 client ID (Google Cloud Console)"),
    ("GOOGLE_OAUTH_CLIENT_SECRET", "Google OAuth2 client secret"),
    ("GOOGLE_SHEET_ID", "Google Sheet ID (from the sheet's URL)"),
    ("GMAIL_FROM", "Gmail address to send from"),
]


def load_env():
    values = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            values[k.strip()] = v.strip()
    return values


def save_env(values):
    lines = ["# Generated by setup_n8n_cold_email.py -- do not commit this file"]
    for key, _ in REQUIRED_KEYS:
        lines.append(f"{key}={values.get(key, '')}")
    ENV_PATH.write_text("\n".join(lines) + "\n")


def prompt(label, existing=None, secret=False):
    suffix = " [keep existing]" if existing else ""
    val = input(f"{label}{suffix}: ").strip()
    if not val and existing:
        return existing
    return val


def run_wizard():
    print("=== n8n Cold Email Workflow Setup Wizard ===\n")
    values = load_env()
    for key, desc in REQUIRED_KEYS:
        values[key] = prompt(desc, values.get(key))
    save_env(values)
    print(f"\nSaved config to {ENV_PATH}\n")
    return values


class N8nClient:
    def __init__(self, base_url, api_key):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update(
            {"X-N8N-API-KEY": api_key, "Content-Type": "application/json"}
        )

    def _url(self, path):
        return f"{self.base_url}/api/v1{path}"

    def test_connection(self):
        r = self.session.get(self._url("/workflows?limit=1"), timeout=15)
        r.raise_for_status()
        return True

    def create_credential(self, name, cred_type, data):
        r = self.session.post(
            self._url("/credentials"),
            json={"name": name, "type": cred_type, "data": data},
            timeout=15,
        )
        r.raise_for_status()
        return r.json()

    def create_workflow(self, workflow):
        r = self.session.post(self._url("/workflows"), json=workflow, timeout=30)
        r.raise_for_status()
        return r.json()

    def activate_workflow(self, workflow_id):
        r = self.session.post(self._url(f"/workflows/{workflow_id}/activate"), timeout=15)
        r.raise_for_status()
        return r.json()

    def list_executions(self, workflow_id, limit=5):
        r = self.session.get(
            self._url(f"/executions?workflowId={workflow_id}&limit={limit}"), timeout=15
        )
        r.raise_for_status()
        return r.json()


def validate(name, cond, hint=""):
    status = "OK" if cond else "FAIL"
    print(f"  [{status}] {name}" + (f" -- {hint}" if hint and not cond else ""))
    return cond


def build_workflow(values):
    """Return the n8n workflow JSON: Cron -> Sheets Read -> Filter -> Claude
    (HTTP Request) -> Gmail Send -> Sheets Update, with an error branch."""

    claude_cred_name = "Claude API (cold email)"
    google_oauth_cred_name = "Google OAuth2 (cold email)"

    nodes = [
        {
            "id": "cron",
            "name": "Daily 9AM Trigger",
            "type": "n8n-nodes-base.cron",
            "typeVersion": 1,
            "position": [0, 0],
            "parameters": {"triggerTimes": {"item": [{"hour": 9, "minute": 0}]}},
        },
        {
            "id": "readSheet",
            "name": "Read Leads Sheet",
            "type": "n8n-nodes-base.googleSheets",
            "typeVersion": 4,
            "position": [220, 0],
            "parameters": {
                "operation": "read",
                "documentId": {"__rl": True, "value": values["GOOGLE_SHEET_ID"], "mode": "id"},
                "sheetName": {"__rl": True, "value": "Sheet1", "mode": "name"},
                "options": {},
            },
            "credentials": {"googleSheetsOAuth2Api": {"name": google_oauth_cred_name}},
        },
        {
            "id": "filterNotSent",
            "name": "Filter Status = Not Sent",
            "type": "n8n-nodes-base.filter",
            "typeVersion": 2,
            "position": [440, 0],
            "parameters": {
                "conditions": {
                    "options": {"caseSensitive": True, "leftValue": "", "typeValidation": "strict"},
                    "conditions": [
                        {
                            "leftValue": "={{$json.Status}}",
                            "rightValue": "Not Sent",
                            "operator": {"type": "string", "operation": "equals"},
                        }
                    ],
                    "combinator": "and",
                }
            },
        },
        {
            "id": "claudePersonalize",
            "name": "Claude - Personalize Email",
            "type": "n8n-nodes-base.httpRequest",
            "typeVersion": 4.2,
            "position": [660, 0],
            "parameters": {
                "method": "POST",
                "url": "https://api.anthropic.com/v1/messages",
                "sendHeaders": True,
                "headerParameters": {
                    "parameters": [
                        {"name": "x-api-key", "value": "={{$credentials.claudeApi.apiKey}}"},
                        {"name": "anthropic-version", "value": "2023-06-01"},
                        {"name": "content-type", "value": "application/json"},
                    ]
                },
                "sendBody": True,
                "specifyBody": "json",
                "jsonBody": (
                    "={{ JSON.stringify({\n"
                    "  model: 'claude-sonnet-5',\n"
                    "  max_tokens: 400,\n"
                    "  messages: [{\n"
                    "    role: 'user',\n"
                    "    content: `Write a short, personalized cold email to "
                    "${$json.FirstName} at ${$json.Company} (${$json.Title}). "
                    "Keep it under 120 words, friendly, no fluff, one clear CTA. "
                    "Return only the email body.`\n"
                    "  }]\n"
                    "}) }}"
                ),
                "options": {"timeout": 30000},
            },
            "credentials": {"claudeApi": {"name": claude_cred_name}},
            "onError": "continueErrorOutput",
        },
        {
            "id": "extractEmailBody",
            "name": "Extract Email Body",
            "type": "n8n-nodes-base.set",
            "typeVersion": 3.4,
            "position": [880, 0],
            "parameters": {
                "assignments": {
                    "assignments": [
                        {
                            "name": "emailBody",
                            "type": "string",
                            "value": "={{$json.content[0].text}}",
                        }
                    ]
                }
            },
        },
        {
            "id": "sendGmail",
            "name": "Send via Gmail",
            "type": "n8n-nodes-base.gmail",
            "typeVersion": 2.1,
            "position": [1100, 0],
            "parameters": {
                "sendTo": "={{$json.Email}}",
                "subject": "={{'Quick question, ' + $json.FirstName}}",
                "message": "={{$json.emailBody}}",
                "options": {"senderName": values["GMAIL_FROM"]},
            },
            "credentials": {"gmailOAuth2": {"name": google_oauth_cred_name}},
            "onError": "continueErrorOutput",
        },
        {
            "id": "updateSheet",
            "name": "Update Status = Sent",
            "type": "n8n-nodes-base.googleSheets",
            "typeVersion": 4,
            "position": [1320, 0],
            "parameters": {
                "operation": "update",
                "documentId": {"__rl": True, "value": values["GOOGLE_SHEET_ID"], "mode": "id"},
                "sheetName": {"__rl": True, "value": "Sheet1", "mode": "name"},
                "columns": {
                    "mappingMode": "defineBelow",
                    "value": {
                        "Status": "Sent",
                        "DateSent": "={{$now.toISO()}}",
                    },
                    "matchingColumns": ["Email"],
                },
            },
            "credentials": {"googleSheetsOAuth2Api": {"name": google_oauth_cred_name}},
        },
        {
            "id": "logError",
            "name": "Log Error Row",
            "type": "n8n-nodes-base.googleSheets",
            "typeVersion": 4,
            "position": [1100, 260],
            "parameters": {
                "operation": "update",
                "documentId": {"__rl": True, "value": values["GOOGLE_SHEET_ID"], "mode": "id"},
                "sheetName": {"__rl": True, "value": "Sheet1", "mode": "name"},
                "columns": {
                    "mappingMode": "defineBelow",
                    "value": {"Status": "Error"},
                    "matchingColumns": ["Email"],
                },
            },
            "credentials": {"googleSheetsOAuth2Api": {"name": google_oauth_cred_name}},
        },
    ]

    connections = {
        "Daily 9AM Trigger": {"main": [[{"node": "Read Leads Sheet", "type": "main", "index": 0}]]},
        "Read Leads Sheet": {
            "main": [[{"node": "Filter Status = Not Sent", "type": "main", "index": 0}]]
        },
        "Filter Status = Not Sent": {
            "main": [[{"node": "Claude - Personalize Email", "type": "main", "index": 0}]]
        },
        "Claude - Personalize Email": {
            "main": [
                [{"node": "Extract Email Body", "type": "main", "index": 0}],
                [{"node": "Log Error Row", "type": "main", "index": 0}],
            ]
        },
        "Extract Email Body": {"main": [[{"node": "Send via Gmail", "type": "main", "index": 0}]]},
        "Send via Gmail": {
            "main": [
                [{"node": "Update Status = Sent", "type": "main", "index": 0}],
                [{"node": "Log Error Row", "type": "main", "index": 0}],
            ]
        },
    }

    return {
        "name": "Cold Email Automation (Apollo -> Claude -> Sheets -> Gmail)",
        "nodes": nodes,
        "connections": connections,
        "settings": {"executionOrder": "v1"},
    }


def main():
    values = run_wizard()

    print("Validating config...")
    ok = True
    ok &= validate("N8N_URL set", bool(values["N8N_URL"]))
    ok &= validate("N8N_API_KEY set", bool(values["N8N_API_KEY"]))
    ok &= validate("CLAUDE_API_KEY set", bool(values["CLAUDE_API_KEY"]))
    ok &= validate("GOOGLE_SHEET_ID set", bool(values["GOOGLE_SHEET_ID"]))
    ok &= validate("GMAIL_FROM looks like an email", "@" in values["GMAIL_FROM"])
    if not ok:
        print("\nFix the missing/invalid values above and re-run.")
        sys.exit(1)

    client = N8nClient(values["N8N_URL"], values["N8N_API_KEY"])

    print("\nTesting n8n connection...")
    try:
        client.test_connection()
        print("  [OK] Connected to n8n API")
    except requests.RequestException as e:
        print(f"  [FAIL] Could not reach n8n at {values['N8N_URL']}: {e}")
        sys.exit(1)

    print("\nCreating credentials...")
    try:
        claude_cred = client.create_credential(
            "Claude API (cold email)",
            "claudeApi",
            {"apiKey": values["CLAUDE_API_KEY"]},
        )
        print("  [OK] Claude API credential created")
    except requests.RequestException as e:
        print(f"  [FAIL] Claude credential creation failed: {e}")
        sys.exit(1)

    try:
        google_cred = client.create_credential(
            "Google OAuth2 (cold email)",
            "googleSheetsOAuth2Api",
            {
                "clientId": values["GOOGLE_OAUTH_CLIENT_ID"],
                "clientSecret": values["GOOGLE_OAUTH_CLIENT_SECRET"],
            },
        )
        print("  [OK] Google OAuth2 credential shell created")
        print(
            "  [ACTION REQUIRED] Open "
            f"{values['N8N_URL'].rstrip('/')}/credentials to click "
            "'Connect my account' for 'Google OAuth2 (cold email)' "
            "(needed for both Sheets and Gmail nodes) -- this step requires "
            "a browser and cannot be automated via the API."
        )
    except requests.RequestException as e:
        print(f"  [FAIL] Google credential creation failed: {e}")
        sys.exit(1)

    print("\nBuilding and deploying workflow...")
    workflow = build_workflow(values)
    try:
        created = client.create_workflow(workflow)
        workflow_id = created["id"]
        print(f"  [OK] Workflow created (id: {workflow_id})")
    except requests.RequestException as e:
        print(f"  [FAIL] Workflow creation failed: {e}")
        sys.exit(1)

    print(
        "\nBefore activating: complete the Google OAuth connection above, "
        "then this script will activate the workflow."
    )
    input("Press Enter once the Google OAuth2 credential shows 'Connected' in n8n...")

    try:
        client.activate_workflow(workflow_id)
        print("  [OK] Workflow activated (cron will fire daily at 9:00 AM)")
    except requests.RequestException as e:
        print(f"  [FAIL] Activation failed: {e}")
        print(
            "  You can activate manually in the n8n editor once the Google "
            "credential is connected."
        )
        sys.exit(1)

    print(
        "\nTo test now with sample data: open the workflow in the n8n editor "
        "and click 'Execute Workflow' -- this exercises the full "
        "Sheets -> Claude -> Gmail -> Sheets chain against one 'Not Sent' row "
        "without waiting for the 9 AM cron."
    )
    print(f"Editor: {values['N8N_URL'].rstrip('/')}/workflow/{workflow_id}")

    print("\n=== Setup complete ===")
    print(f"Workflow ID: {workflow_id}")
    print("Nodes: Cron -> Read Sheet -> Filter -> Claude -> Send Gmail -> Update Sheet")
    print("Error handling: Claude/Gmail failures route to 'Log Error Row' (Status=Error)")


if __name__ == "__main__":
    main()
